# Site
repository: mrsauravs/cv
# Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)

# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Saurabh Sugandh
title: Senior Technical Writer
email: mrsauravs@gmail.com
phone: (+91) 9535791480
website: https://inverselattice.com

darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  mrsauravs
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: saurabh-sugandh-97280148
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: Link name
# icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
# url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Profile #(Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Experienced in information gathering, business analysis, networking, documentation, and leading projects with an overall experience of over eight years in IT. I’m well versed with various documentation tools such as Oxygen XML Editor, PTC Arbortext Editor, Adobe FrameMaker, Adobe RoboHelp, and Microsoft Word. I constantly work to improve user-content experience and closely involved in various initiatives at my workplace. I’ve a sound knowledge of computer networks. I also maintain a blog that covers a wide veriety of topics and occasionally ponder over various linux flavors to test their features and usability.

# You can even add paragraphs by using empty lines like this and add anything else markdown supports such as
#    - Lists
#    - Tables
#    - <a href="google.com">Links</a>
#    - Images

# Education Section
education_title: Academics

# Experience Section
experience_title: Professional #(Use this to override about experience section title)

# Projects Section
projects_title: Projects #(Use this to override about projects section title)


# More Section
more_title: More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Alongside my skills in technical product documentation, I have other interests and hobbies too:
   - Review movie titles
   - Create and work on Arduino projects
   - Follow cricket

#  Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme 
#(Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
